### PR TITLE
add 43 new devices

### PR DESCRIPTION
**Pull request by FabianTerhorst**
add 43 new devices

### CODE REVIEW

**Comment by tslamic** [comment]
Hi Fabian,

many many thanks for your contribution. I reviewed the pull request; I feel we should not merge `when no fallback is given return device model` commit - `null` might be a legitimate default value and more importantly, it could cause backwards compatibility issues.

To ease the merge, could you please create another pull request with only the `add new devices` commit?

Thanks again!

Cheers,
Tadej

**Comment by FabianTerhorst** [comment]
i updated the pull request

**Comment by tslamic** [comment]
Thanks for a quick update Fabian. 

If you have time, could you please update the `.travis.yml` file and ensure CI builds the project successfully? I think updating the SKD version and build tools should do the trick.

I’ll merge this as soon as I have access to my machine, so I can push to mvn right away. 

Cheers,
Tadej

**Comment by FabianTerhorst** [comment]
travis build successfully

**Pull request merged**
